default: &default
  adapter: mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("LOCATEIT_DB_USER") { 'root' } %>
  password: <%= ENV.fetch("LOCATEIT_DB_PASS") { 'password' } %>
  host:     <%= ENV.fetch("LOCATEIT_DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: locateit_development

test:
  <<: *default
  database: locateit_test

production:
  <<: *default
  database: locateit_production
